### ISSUE TITLE
使用中的问题

### ISSUE THREAD

**Issue by Yvacineank-G** [WhymustIhaveaname/ByrBtAutoDownloader#2]
楼主，我运行你的脚本没法运行啊。。

21/09/10 15:11:13 [INFO,ls:412] There are now 0 seeds with total size 0.0 GB (after fully downloaded).
Traceback (most recent call last):
  File "byrbt.py", line 450, in <module>
    AutoDown.ls()
  File "byrbt.py", line 416, in ls
    avg_ratio=sum([i['value']*i['size'] for i in exist_seeds])/torrent_size
ZeroDivisionError: division by zero

错误是这个

**Comment by WhymustIhaveaname** [comment]
emmm.... 你还没下任何种子，所以在 `avg_ratio=sum([i['value']*i['size'] for i in exist_seeds])/torrent_size` 中的 `torrent_size` 是零。稍等我改一下

**Comment by WhymustIhaveaname** [comment]
已经解决了，`git pull` 最新版脚本即可（配置文件不会被覆盖）。这个错误应该只会影响`--ls`命令，或者下点东西就没有这个错误了。祝使用愉快。

**Comment by Yvacineank-G** [comment]
谢谢老哥，我刚刚一通操作程序也跑起来了，谢谢！BUPTer都是好兄弟！
非常感谢
非常感谢
非常感谢！
（重要的事情说三遍）

**Comment by Yvacineank-G** [comment]
不过，为啥我git pull没有执行起来呢？

**Comment by WhymustIhaveaname** [comment]
两种可能
1. `git pull` 没有在程序根目录下执行，比如在程序的子文件夹或者父文件夹中执行是不行的
2. 程序是下的zip再解压缩的，这种情况下没有git记录，程序一旦更新，需要重新下zip解压缩再把配置文件复制粘贴过去

刚才做的更改还挺重要的（北邮人的新域名），建议下载最新版，否则它会认为i自己下载的种子是0.0GB，然后一直下一直下，直到把磁盘占满，自动清除也不能正常运作。

**Comment by Yvacineank-G** [comment]
谢谢，我在看看，非常打搅您了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WhymustIhaveaname/ByrBtAutoDownloader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月10日(星期五) 晚上7:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WhymustIhaveaname/ByrBtAutoDownloader] 报错！ (#2)





 
两种可能
  
git pull 没有在程序根目录下执行，比如在程序的子文件夹或者父文件夹中执行是不行的
 
程序是下的zip再解压缩的，这种情况下没有git记录，程序一旦更新，需要重新下zip解压缩再把配置文件复制粘贴过去
  
刚才做的更改还挺重要的（北邮人的新域名），建议下载最新版，否则它会认为i自己下载的种子是0.0GB，然后一直下一直下，直到把磁盘占满，自动清除也不能正常运作。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Yvacineank-G** [comment]
您好，请问一下，为什么我vim出不来配置，但是用sudo cat能够看到里面的内容呢？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WhymustIhaveaname/ByrBtAutoDownloader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月10日(星期五) 晚上7:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WhymustIhaveaname/ByrBtAutoDownloader] 报错！ (#2)





 
两种可能
  
git pull 没有在程序根目录下执行，比如在程序的子文件夹或者父文件夹中执行是不行的
 
程序是下的zip再解压缩的，这种情况下没有git记录，程序一旦更新，需要重新下zip解压缩再把配置文件复制粘贴过去
  
刚才做的更改还挺重要的（北邮人的新域名），建议下载最新版，否则它会认为i自己下载的种子是0.0GB，然后一直下一直下，直到把磁盘占满，自动清除也不能正常运作。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WhymustIhaveaname** [comment]
No idea. 您可以试试`vi`或者`nano`.

**Comment by Yvacineank-G** [comment]
好的，您好，请问下您的crontab 能自动执行吗？我单独执行脚本命令可以，但是好像不能自动执行，是只加25 */6 * * * cd /home/dAlembert/byrbt_bot &amp;&amp; ./byrbt.py --main
一行代码吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WhymustIhaveaname/ByrBtAutoDownloader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月10日(星期五) 晚上10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WhymustIhaveaname/ByrBtAutoDownloader] 报错！ (#2)





 
No idea. 您可以试试vi或者nano.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WhymustIhaveaname** [comment]
是的，但路径要记得改一下。让crontab跑起来需要一点点但是只是一点点经验，你可以

1. 加一点输出看看到底执行到哪里，比如
```
25 */6 * * * cd 存程序的文件夹;  date>>crontab.log; ./byrbt.py --main; echo "finish">>crontab.log
```
`date>>crontab.log` 是说将当前时间写入`crontab.log`这个文件，`echo "finish">>crontab.log`是说将“finish”写入`crontab.log`。那么当你打开`crontab.log`应该会看到
```
Sun 12 Sep 2021 06:25:01 PM CST
finish
Sun 12 Sep 2021 12:25:01 PM CST
finish
```
2. 复制crontab的全部命令部分然后在`/`下运行，看看能否正常执行。

**Comment by Yvacineank-G** [comment]
您好，多次打搅，非常的不好意思，



为了测试，我把程序调整成这样了，输出结果如下图，但是我的种子并没有任何增加，请问这是什么情况呢，我







所以我觉得是否是程序的问题呢？但是我进入目录执行，一点问题都没有，所以代码是过关的，您知道这是什么情况吗？如果可以的话，很冒昧，我想看下您的crontab -e配置，非常厚脸皮了。。。。









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WhymustIhaveaname/ByrBtAutoDownloader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月12日(星期天) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WhymustIhaveaname/ByrBtAutoDownloader] 报错！ (#2)





 
是的，但路径要记得改一下。让crontab跑起来需要一点点但是只是一点点经验，你可以
  
加一点输出看看到底执行到哪里，比如
  25 */6 * * * cd 存程序的文件夹;  date&gt;&gt;crontab.log; ./byrbt.py --main; echo "finish"&gt;&gt;crontab.log  
date&gt;&gt;crontab.log 是说将当前时间写入crontab.log这个文件，echo "finish"&gt;&gt;crontab.log是说将“finish”写入crontab.log。那么当你打开crontab.log应该会看到
 Sun 12 Sep 2021 06:25:01 PM CST finish Sun 12 Sep 2021 12:25:01 PM CST finish   
复制crontab的全部命令部分然后在/下运行，看看能否正常执行。
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WhymustIhaveaname** [comment]
抱歉我没看到图片，我在外面回去再贴crontab -l，在目录下执行有种子增加吗？

**Comment by Yvacineank-G** [comment]
没有欸，是执行成功的，种子并没有增加，如果不介意，可以加个微信吗？我微信号是：18796498148






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WhymustIhaveaname/ByrBtAutoDownloader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月12日(星期天) 晚上6:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WhymustIhaveaname/ByrBtAutoDownloader] 报错！ (#2)





 
抱歉我没看到图片，我在外面回去再贴crontab -l，在目录下执行有种子增加吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WhymustIhaveaname** [comment]
已家，所以把那条涉及您隐私的回复删除了

**Comment by WhymustIhaveaname** [comment]
经过微信沟通，现在已经work了，教训是

1. 更新代码时千万不要复制粘贴自己认为更新了的部分，那样是找不全的
2. bash环境有anaconda时crontab脚本也要加anaconda，最好压根就不要用anaconda
